language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build:prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 3fcb6ad72e064e80ceff740096ff584b112ba50c
  local_dir: dist
  on:
    branch: master
