language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build:prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 53b76cefd8b0e206e3c8eb2eb1a6e241b6b1c380
  local_dir: dist
  on:
    branch: master
